import Head from 'next/head';

import { Box } from '@mui/material';
import { firstLetterToUpperCase } from '@/client/helpers/strings';
import { Typography } from '@mui/material';
import { docsPaths } from '@/client/utils/paths';
import { Link } from '@/client/components/global/Link/Link';

export default function Home() {
  // function calculateBalance(years: any, rate: number) {
  //   const monthlyDeposit = 1000;
  //   const annualInterestRate = rate; //0.1;
  //   const months = years * 12;

  //   let balance = 0;

  //   for (let i = 0; i < months; i++) {
  //     balance += monthlyDeposit;

  //     if (!((i + 1) % 12)) {
  //       const monthlyInterest = balance * annualInterestRate;
  //       balance += monthlyInterest;
  //     }
  //   }

  //   return balance.toFixed(2);
  // }
  // console.log('==');
  // console.log('==');

  // console.log('-- ' + calculateBalance(20, 0));
  // console.log('-- ' + calculateBalance(20, 0.02));
  // console.log('-- ' + calculateBalance(20, 0.04));
  // console.log('-- ' + calculateBalance(20, 0.06));
  // console.log('-- ' + calculateBalance(20, 0.08));
  // console.log('-- ' + calculateBalance(20, 0.1));

  return (
    <>
      <Head>
        <title>My documentationsp</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Box
        alignItems={'center'}
        display={'flex'}
        flexDirection='column'
        gap='48px'
        height='100%'
        justifyContent='center'
      >
        <Typography variant='h2' color='primary' textAlign={'center'}>
          Welcome in my documentations
        </Typography>
        <Typography variant='subtitle1' textAlign={'center'}>
          Here you will find the most important concepts explained by way of
          example related to:
        </Typography>

        <ul>
          {Object.entries(docsPaths).map(([key, path]) => (
            <li key={key}>
              <Link href={path}>{firstLetterToUpperCase(key)}</Link>
            </li>
          ))}
        </ul>
      </Box>
    </>
  );
}
